formfiller.names=test
formfiller.http.connect-timeout-seconds=30
formfiller.http.read-timeout-seconds=60

formfiller.test.enabled=true
formfiller.test.link=https://docs.google.com/forms/d/e/1FAIpQLSfAEVopyw5eBXm5zBMxAZMh8-iyCaJkd6RmClPPtax3qMoCyA/viewform?usp=header
formfiller.test.questions-file=C:/Work/ide-projects/java/gform-filler/config/questionnaires/questionnaire.questions.properties
formfiller.test.interval-seconds=1
formfiller.test.fill-count=1

